###############################################################################
#
# Bash remediation role for profile standard
# Profile Title:  Standard System Security Profile for Ubuntu 14
# Profile Description:
# This profile contains rules to ensure standard security baseline
# of a Ubuntu 14 system. Regardless of your system's workload
# all of these checks should pass.
#
# Benchmark ID:  UBUNTU-TRUSTY
# Benchmark Version:  0.1.40
#
# XCCDF Version:  1.1
#
# This file was generated by OpenSCAP 1.2.17 using:
# 	$ oscap xccdf generate fix --profile standard --template urn:xccdf:fix:script:sh xccdf-file.xml 
#
# This script is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
# How to apply this remediation role:
# $ sudo ./remediation-role.sh
#
###############################################################################

###############################################################################
# BEGIN fix (1 / 36) for 'package_ntp_installed'
###############################################################################
(>&2 echo "Remediating rule 1/36: 'package_ntp_installed'")
(>&2 echo "FIX FOR THIS RULE 'package_ntp_installed' IS MISSING!")
# END fix for 'package_ntp_installed'

###############################################################################
# BEGIN fix (2 / 36) for 'service_ntp_enabled'
###############################################################################
(>&2 echo "Remediating rule 2/36: 'service_ntp_enabled'")
(>&2 echo "FIX FOR THIS RULE 'service_ntp_enabled' IS MISSING!")
# END fix for 'service_ntp_enabled'

###############################################################################
# BEGIN fix (3 / 36) for 'service_cron_enabled'
###############################################################################
(>&2 echo "Remediating rule 3/36: 'service_cron_enabled'")
(>&2 echo "FIX FOR THIS RULE 'service_cron_enabled' IS MISSING!")
# END fix for 'service_cron_enabled'

###############################################################################
# BEGIN fix (4 / 36) for 'service_auditd_enabled'
###############################################################################
(>&2 echo "Remediating rule 4/36: 'service_auditd_enabled'")
(>&2 echo "FIX FOR THIS RULE 'service_auditd_enabled' IS MISSING!")
# END fix for 'service_auditd_enabled'

###############################################################################
# BEGIN fix (5 / 36) for 'package_auditd_installed'
###############################################################################
(>&2 echo "Remediating rule 5/36: 'package_auditd_installed'")
(>&2 echo "FIX FOR THIS RULE 'package_auditd_installed' IS MISSING!")
# END fix for 'package_auditd_installed'

###############################################################################
# BEGIN fix (6 / 36) for 'package_cron_installed'
###############################################################################
(>&2 echo "Remediating rule 6/36: 'package_cron_installed'")
(>&2 echo "FIX FOR THIS RULE 'package_cron_installed' IS MISSING!")
# END fix for 'package_cron_installed'

###############################################################################
# BEGIN fix (7 / 36) for 'package_nis_removed'
###############################################################################
(>&2 echo "Remediating rule 7/36: 'package_nis_removed'")
# Function to remove packages on RHEL, Fedora, Debian, and possibly other systems.
#
# Example Call(s):
#
#     package_remove telnet-server
#
function package_remove {

# Load function arguments into local variables
local package="$1"

# Check sanity of the input
if [ $# -ne "1" ]
then
  echo "Usage: package_remove 'package_name'"
  echo "Aborting."
  exit 1
fi

if which dnf ; then
  if rpm -q --quiet "$package"; then
    dnf remove -y "$package"
  fi
elif which yum ; then
  if rpm -q --quiet "$package"; then
    yum remove -y "$package"
  fi
elif which apt-get ; then
  apt-get remove -y "$package"
else
  echo "Failed to detect available packaging system, tried dnf, yum and apt-get!"
  echo "Aborting."
  exit 1
fi

}

package_remove nis
# END fix for 'package_nis_removed'

###############################################################################
# BEGIN fix (8 / 36) for 'package_inetutils-telnetd_removed'
###############################################################################
(>&2 echo "Remediating rule 8/36: 'package_inetutils-telnetd_removed'")
# Function to remove packages on RHEL, Fedora, Debian, and possibly other systems.
#
# Example Call(s):
#
#     package_remove telnet-server
#
function package_remove {

# Load function arguments into local variables
local package="$1"

# Check sanity of the input
if [ $# -ne "1" ]
then
  echo "Usage: package_remove 'package_name'"
  echo "Aborting."
  exit 1
fi

if which dnf ; then
  if rpm -q --quiet "$package"; then
    dnf remove -y "$package"
  fi
elif which yum ; then
  if rpm -q --quiet "$package"; then
    yum remove -y "$package"
  fi
elif which apt-get ; then
  apt-get remove -y "$package"
else
  echo "Failed to detect available packaging system, tried dnf, yum and apt-get!"
  echo "Aborting."
  exit 1
fi

}

package_remove inetutils-telnetd
# END fix for 'package_inetutils-telnetd_removed'

###############################################################################
# BEGIN fix (9 / 36) for 'package_ntpdate_removed'
###############################################################################
(>&2 echo "Remediating rule 9/36: 'package_ntpdate_removed'")
# Function to remove packages on RHEL, Fedora, Debian, and possibly other systems.
#
# Example Call(s):
#
#     package_remove telnet-server
#
function package_remove {

# Load function arguments into local variables
local package="$1"

# Check sanity of the input
if [ $# -ne "1" ]
then
  echo "Usage: package_remove 'package_name'"
  echo "Aborting."
  exit 1
fi

if which dnf ; then
  if rpm -q --quiet "$package"; then
    dnf remove -y "$package"
  fi
elif which yum ; then
  if rpm -q --quiet "$package"; then
    yum remove -y "$package"
  fi
elif which apt-get ; then
  apt-get remove -y "$package"
else
  echo "Failed to detect available packaging system, tried dnf, yum and apt-get!"
  echo "Aborting."
  exit 1
fi

}

package_remove ntpdate
# END fix for 'package_ntpdate_removed'

###############################################################################
# BEGIN fix (10 / 36) for 'package_telnetd-ssl_removed'
###############################################################################
(>&2 echo "Remediating rule 10/36: 'package_telnetd-ssl_removed'")
# Function to remove packages on RHEL, Fedora, Debian, and possibly other systems.
#
# Example Call(s):
#
#     package_remove telnet-server
#
function package_remove {

# Load function arguments into local variables
local package="$1"

# Check sanity of the input
if [ $# -ne "1" ]
then
  echo "Usage: package_remove 'package_name'"
  echo "Aborting."
  exit 1
fi

if which dnf ; then
  if rpm -q --quiet "$package"; then
    dnf remove -y "$package"
  fi
elif which yum ; then
  if rpm -q --quiet "$package"; then
    yum remove -y "$package"
  fi
elif which apt-get ; then
  apt-get remove -y "$package"
else
  echo "Failed to detect available packaging system, tried dnf, yum and apt-get!"
  echo "Aborting."
  exit 1
fi

}

package_remove telnetd-ssl
# END fix for 'package_telnetd-ssl_removed'

###############################################################################
# BEGIN fix (11 / 36) for 'package_telnetd_removed'
###############################################################################
(>&2 echo "Remediating rule 11/36: 'package_telnetd_removed'")
# Function to remove packages on RHEL, Fedora, Debian, and possibly other systems.
#
# Example Call(s):
#
#     package_remove telnet-server
#
function package_remove {

# Load function arguments into local variables
local package="$1"

# Check sanity of the input
if [ $# -ne "1" ]
then
  echo "Usage: package_remove 'package_name'"
  echo "Aborting."
  exit 1
fi

if which dnf ; then
  if rpm -q --quiet "$package"; then
    dnf remove -y "$package"
  fi
elif which yum ; then
  if rpm -q --quiet "$package"; then
    yum remove -y "$package"
  fi
elif which apt-get ; then
  apt-get remove -y "$package"
else
  echo "Failed to detect available packaging system, tried dnf, yum and apt-get!"
  echo "Aborting."
  exit 1
fi

}

package_remove telnetd
# END fix for 'package_telnetd_removed'

###############################################################################
# BEGIN fix (12 / 36) for 'sshd_allow_only_protocol2'
###############################################################################
(>&2 echo "Remediating rule 12/36: 'sshd_allow_only_protocol2'")
(>&2 echo "FIX FOR THIS RULE 'sshd_allow_only_protocol2' IS MISSING!")
# END fix for 'sshd_allow_only_protocol2'

###############################################################################
# BEGIN fix (13 / 36) for 'sshd_disable_empty_passwords'
###############################################################################
(>&2 echo "Remediating rule 13/36: 'sshd_disable_empty_passwords'")
(>&2 echo "FIX FOR THIS RULE 'sshd_disable_empty_passwords' IS MISSING!")
# END fix for 'sshd_disable_empty_passwords'

###############################################################################
# BEGIN fix (14 / 36) for 'sshd_set_keepalive'
###############################################################################
(>&2 echo "Remediating rule 14/36: 'sshd_set_keepalive'")
(>&2 echo "FIX FOR THIS RULE 'sshd_set_keepalive' IS MISSING!")
# END fix for 'sshd_set_keepalive'

###############################################################################
# BEGIN fix (15 / 36) for 'sshd_set_idle_timeout'
###############################################################################
(>&2 echo "Remediating rule 15/36: 'sshd_set_idle_timeout'")
(>&2 echo "FIX FOR THIS RULE 'sshd_set_idle_timeout' IS MISSING!")
# END fix for 'sshd_set_idle_timeout'

###############################################################################
# BEGIN fix (16 / 36) for 'sshd_disable_root_login'
###############################################################################
(>&2 echo "Remediating rule 16/36: 'sshd_disable_root_login'")
(>&2 echo "FIX FOR THIS RULE 'sshd_disable_root_login' IS MISSING!")
# END fix for 'sshd_disable_root_login'

###############################################################################
# BEGIN fix (17 / 36) for 'ensure_logrotate_activated'
###############################################################################
(>&2 echo "Remediating rule 17/36: 'ensure_logrotate_activated'")
(>&2 echo "FIX FOR THIS RULE 'ensure_logrotate_activated' IS MISSING!")
# END fix for 'ensure_logrotate_activated'

###############################################################################
# BEGIN fix (18 / 36) for 'rsyslog_files_groupownership'
###############################################################################
(>&2 echo "Remediating rule 18/36: 'rsyslog_files_groupownership'")
(>&2 echo "FIX FOR THIS RULE 'rsyslog_files_groupownership' IS MISSING!")
# END fix for 'rsyslog_files_groupownership'

###############################################################################
# BEGIN fix (19 / 36) for 'rsyslog_files_ownership'
###############################################################################
(>&2 echo "Remediating rule 19/36: 'rsyslog_files_ownership'")
(>&2 echo "FIX FOR THIS RULE 'rsyslog_files_ownership' IS MISSING!")
# END fix for 'rsyslog_files_ownership'

###############################################################################
# BEGIN fix (20 / 36) for 'rsyslog_files_permissions'
###############################################################################
(>&2 echo "Remediating rule 20/36: 'rsyslog_files_permissions'")
(>&2 echo "FIX FOR THIS RULE 'rsyslog_files_permissions' IS MISSING!")
# END fix for 'rsyslog_files_permissions'

###############################################################################
# BEGIN fix (21 / 36) for 'package_rsyslog_installed'
###############################################################################
(>&2 echo "Remediating rule 21/36: 'package_rsyslog_installed'")
(>&2 echo "FIX FOR THIS RULE 'package_rsyslog_installed' IS MISSING!")
# END fix for 'package_rsyslog_installed'

###############################################################################
# BEGIN fix (22 / 36) for 'service_rsyslog_enabled'
###############################################################################
(>&2 echo "Remediating rule 22/36: 'service_rsyslog_enabled'")
(>&2 echo "FIX FOR THIS RULE 'service_rsyslog_enabled' IS MISSING!")
# END fix for 'service_rsyslog_enabled'

###############################################################################
# BEGIN fix (23 / 36) for 'file_permissions_systemmap'
###############################################################################
(>&2 echo "Remediating rule 23/36: 'file_permissions_systemmap'")
(>&2 echo "FIX FOR THIS RULE 'file_permissions_systemmap' IS MISSING!")
# END fix for 'file_permissions_systemmap'

###############################################################################
# BEGIN fix (24 / 36) for 'file_permissions_etc_shadow'
###############################################################################
(>&2 echo "Remediating rule 24/36: 'file_permissions_etc_shadow'")

chmod 0640 /etc/shadow
# END fix for 'file_permissions_etc_shadow'

###############################################################################
# BEGIN fix (25 / 36) for 'file_permissions_etc_passwd'
###############################################################################
(>&2 echo "Remediating rule 25/36: 'file_permissions_etc_passwd'")

chmod 0644 /etc/passwd
# END fix for 'file_permissions_etc_passwd'

###############################################################################
# BEGIN fix (26 / 36) for 'file_permissions_etc_group'
###############################################################################
(>&2 echo "Remediating rule 26/36: 'file_permissions_etc_group'")

chmod 0644 /etc/group
# END fix for 'file_permissions_etc_group'

###############################################################################
# BEGIN fix (27 / 36) for 'file_permissions_etc_gshadow'
###############################################################################
(>&2 echo "Remediating rule 27/36: 'file_permissions_etc_gshadow'")

chmod 0640 /etc/gshadow
# END fix for 'file_permissions_etc_gshadow'

###############################################################################
# BEGIN fix (28 / 36) for 'sysctl_kernel_randomize_va_space'
###############################################################################
(>&2 echo "Remediating rule 28/36: 'sysctl_kernel_randomize_va_space'")
(>&2 echo "FIX FOR THIS RULE 'sysctl_kernel_randomize_va_space' IS MISSING!")
# END fix for 'sysctl_kernel_randomize_va_space'

###############################################################################
# BEGIN fix (29 / 36) for 'sysctl_fs_suid_dumpable'
###############################################################################
(>&2 echo "Remediating rule 29/36: 'sysctl_fs_suid_dumpable'")
(>&2 echo "FIX FOR THIS RULE 'sysctl_fs_suid_dumpable' IS MISSING!")
# END fix for 'sysctl_fs_suid_dumpable'

###############################################################################
# BEGIN fix (30 / 36) for 'sysctl_fs_protected_symlinks'
###############################################################################
(>&2 echo "Remediating rule 30/36: 'sysctl_fs_protected_symlinks'")
(>&2 echo "FIX FOR THIS RULE 'sysctl_fs_protected_symlinks' IS MISSING!")
# END fix for 'sysctl_fs_protected_symlinks'

###############################################################################
# BEGIN fix (31 / 36) for 'sysctl_fs_protected_hardlinks'
###############################################################################
(>&2 echo "Remediating rule 31/36: 'sysctl_fs_protected_hardlinks'")
(>&2 echo "FIX FOR THIS RULE 'sysctl_fs_protected_hardlinks' IS MISSING!")
# END fix for 'sysctl_fs_protected_hardlinks'

###############################################################################
# BEGIN fix (32 / 36) for 'partition_for_tmp'
###############################################################################
(>&2 echo "Remediating rule 32/36: 'partition_for_tmp'")
(>&2 echo "FIX FOR THIS RULE 'partition_for_tmp' IS MISSING!")
# END fix for 'partition_for_tmp'

###############################################################################
# BEGIN fix (33 / 36) for 'partition_for_var_log'
###############################################################################
(>&2 echo "Remediating rule 33/36: 'partition_for_var_log'")
(>&2 echo "FIX FOR THIS RULE 'partition_for_var_log' IS MISSING!")
# END fix for 'partition_for_var_log'

###############################################################################
# BEGIN fix (34 / 36) for 'partition_for_var'
###############################################################################
(>&2 echo "Remediating rule 34/36: 'partition_for_var'")
(>&2 echo "FIX FOR THIS RULE 'partition_for_var' IS MISSING!")
# END fix for 'partition_for_var'

###############################################################################
# BEGIN fix (35 / 36) for 'partition_for_var_log_audit'
###############################################################################
(>&2 echo "Remediating rule 35/36: 'partition_for_var_log_audit'")
(>&2 echo "FIX FOR THIS RULE 'partition_for_var_log_audit' IS MISSING!")
# END fix for 'partition_for_var_log_audit'

###############################################################################
# BEGIN fix (36 / 36) for 'partition_for_home'
###############################################################################
(>&2 echo "Remediating rule 36/36: 'partition_for_home'")
(>&2 echo "FIX FOR THIS RULE 'partition_for_home' IS MISSING!")
# END fix for 'partition_for_home'

