###############################################################################
#
# Bash remediation role for profile anssi_np_nt28_restrictive
# Profile Title:  Profile for ANSSI DAT-NT28 Restrictive Level
# Profile Description:  This profile contains items for GNU/Linux installations exposed to unauthenticated flows or multiple sources.
#
# Benchmark ID:  DEBIAN-8
# Benchmark Version:  0.1.36
#
# XCCDF Version:  1.1
#
# This file was generated by OpenSCAP 1.2.15 using:
# 	$ oscap xccdf generate fix --profile anssi_np_nt28_restrictive --template urn:xccdf:fix:script:sh sds.xml 
#
# This script is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
###############################################################################

###############################################################################
# BEGIN fix (1 / 41) for 'file_permissions_systemmap'
###############################################################################
(>&2 echo "Remediating rule 1/41: 'file_permissions_systemmap'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'file_permissions_systemmap'

###############################################################################
# BEGIN fix (2 / 41) for 'file_permissions_etc_shadow'
###############################################################################
(>&2 echo "Remediating rule 2/41: 'file_permissions_etc_shadow'")
chmod 0640 /etc/shadow
# END fix for 'file_permissions_etc_shadow'

###############################################################################
# BEGIN fix (3 / 41) for 'file_permissions_etc_gshadow'
###############################################################################
(>&2 echo "Remediating rule 3/41: 'file_permissions_etc_gshadow'")
chmod 0640 /etc/gshadow
# END fix for 'file_permissions_etc_gshadow'

###############################################################################
# BEGIN fix (4 / 41) for 'file_permissions_etc_passwd'
###############################################################################
(>&2 echo "Remediating rule 4/41: 'file_permissions_etc_passwd'")
chmod 0644 /etc/passwd
# END fix for 'file_permissions_etc_passwd'

###############################################################################
# BEGIN fix (5 / 41) for 'file_permissions_etc_group'
###############################################################################
(>&2 echo "Remediating rule 5/41: 'file_permissions_etc_group'")
chmod 0644 /etc/group
# END fix for 'file_permissions_etc_group'

###############################################################################
# BEGIN fix (6 / 41) for 'sysctl_fs_suid_dumpable'
###############################################################################
(>&2 echo "Remediating rule 6/41: 'sysctl_fs_suid_dumpable'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sysctl_fs_suid_dumpable'

###############################################################################
# BEGIN fix (7 / 41) for 'sysctl_kernel_randomize_va_space'
###############################################################################
(>&2 echo "Remediating rule 7/41: 'sysctl_kernel_randomize_va_space'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sysctl_kernel_randomize_va_space'

###############################################################################
# BEGIN fix (8 / 41) for 'partition_for_tmp'
###############################################################################
(>&2 echo "Remediating rule 8/41: 'partition_for_tmp'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'partition_for_tmp'

###############################################################################
# BEGIN fix (9 / 41) for 'partition_for_var'
###############################################################################
(>&2 echo "Remediating rule 9/41: 'partition_for_var'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'partition_for_var'

###############################################################################
# BEGIN fix (10 / 41) for 'partition_for_var_log'
###############################################################################
(>&2 echo "Remediating rule 10/41: 'partition_for_var_log'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'partition_for_var_log'

###############################################################################
# BEGIN fix (11 / 41) for 'partition_for_var_log_audit'
###############################################################################
(>&2 echo "Remediating rule 11/41: 'partition_for_var_log_audit'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'partition_for_var_log_audit'

###############################################################################
# BEGIN fix (12 / 41) for 'partition_for_home'
###############################################################################
(>&2 echo "Remediating rule 12/41: 'partition_for_home'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'partition_for_home'

###############################################################################
# BEGIN fix (13 / 41) for 'sysctl_fs_protected_symlinks'
###############################################################################
(>&2 echo "Remediating rule 13/41: 'sysctl_fs_protected_symlinks'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sysctl_fs_protected_symlinks'

###############################################################################
# BEGIN fix (14 / 41) for 'sysctl_fs_protected_hardlinks'
###############################################################################
(>&2 echo "Remediating rule 14/41: 'sysctl_fs_protected_hardlinks'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sysctl_fs_protected_hardlinks'

###############################################################################
# BEGIN fix (15 / 41) for 'sudo_remove_nopasswd'
###############################################################################
(>&2 echo "Remediating rule 15/41: 'sudo_remove_nopasswd'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sudo_remove_nopasswd'

###############################################################################
# BEGIN fix (16 / 41) for 'sudo_remove_no_authenticate'
###############################################################################
(>&2 echo "Remediating rule 16/41: 'sudo_remove_no_authenticate'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sudo_remove_no_authenticate'

###############################################################################
# BEGIN fix (17 / 41) for 'package_rsyslog_installed'
###############################################################################
(>&2 echo "Remediating rule 17/41: 'package_rsyslog_installed'")
# Include source function library.

apt-get install rsyslog
# END fix for 'package_rsyslog_installed'

###############################################################################
# BEGIN fix (18 / 41) for 'service_rsyslog_enabled'
###############################################################################
(>&2 echo "Remediating rule 18/41: 'service_rsyslog_enabled'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'service_rsyslog_enabled'

###############################################################################
# BEGIN fix (19 / 41) for 'rsyslog_files_ownership'
###############################################################################
(>&2 echo "Remediating rule 19/41: 'rsyslog_files_ownership'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'rsyslog_files_ownership'

###############################################################################
# BEGIN fix (20 / 41) for 'rsyslog_files_groupownership'
###############################################################################
(>&2 echo "Remediating rule 20/41: 'rsyslog_files_groupownership'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'rsyslog_files_groupownership'

###############################################################################
# BEGIN fix (21 / 41) for 'rsyslog_files_permissions'
###############################################################################
(>&2 echo "Remediating rule 21/41: 'rsyslog_files_permissions'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'rsyslog_files_permissions'

###############################################################################
# BEGIN fix (22 / 41) for 'package_syslogng_installed'
###############################################################################
(>&2 echo "Remediating rule 22/41: 'package_syslogng_installed'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'package_syslogng_installed'

###############################################################################
# BEGIN fix (23 / 41) for 'service_syslogng_enabled'
###############################################################################
(>&2 echo "Remediating rule 23/41: 'service_syslogng_enabled'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'service_syslogng_enabled'

###############################################################################
# BEGIN fix (24 / 41) for 'ensure_logrotate_activated'
###############################################################################
(>&2 echo "Remediating rule 24/41: 'ensure_logrotate_activated'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'ensure_logrotate_activated'

###############################################################################
# BEGIN fix (25 / 41) for 'package_telnetd_removed'
###############################################################################
(>&2 echo "Remediating rule 25/41: 'package_telnetd_removed'")
# CAUTION: This remediation script will remove telnetd
#	   from the system, and may remove any packages
#	   that depend on telnetd. Execute this
#	   remediation AFTER testing on a non-production
#	   system!

apt-get remove --purge telnetd
# END fix for 'package_telnetd_removed'

###############################################################################
# BEGIN fix (26 / 41) for 'package_inetutils-telnetd_removed'
###############################################################################
(>&2 echo "Remediating rule 26/41: 'package_inetutils-telnetd_removed'")
# CAUTION: This remediation script will remove inetutils-telnetd
#	   from the system, and may remove any packages
#	   that depend on inetutils-telnetd. Execute this
#	   remediation AFTER testing on a non-production
#	   system!

apt-get remove --purge inetutils-telnetd
# END fix for 'package_inetutils-telnetd_removed'

###############################################################################
# BEGIN fix (27 / 41) for 'package_telnetd-ssl_removed'
###############################################################################
(>&2 echo "Remediating rule 27/41: 'package_telnetd-ssl_removed'")
# CAUTION: This remediation script will remove telnetd-ssl
#	   from the system, and may remove any packages
#	   that depend on telnetd-ssl. Execute this
#	   remediation AFTER testing on a non-production
#	   system!

apt-get remove --purge telnetd-ssl
# END fix for 'package_telnetd-ssl_removed'

###############################################################################
# BEGIN fix (28 / 41) for 'package_nis_removed'
###############################################################################
(>&2 echo "Remediating rule 28/41: 'package_nis_removed'")
# CAUTION: This remediation script will remove nis
#	   from the system, and may remove any packages
#	   that depend on nis. Execute this
#	   remediation AFTER testing on a non-production
#	   system!

apt-get remove --purge nis
# END fix for 'package_nis_removed'

###############################################################################
# BEGIN fix (29 / 41) for 'package_ntpdate_removed'
###############################################################################
(>&2 echo "Remediating rule 29/41: 'package_ntpdate_removed'")
# CAUTION: This remediation script will remove ntpdate
#	   from the system, and may remove any packages
#	   that depend on ntpdate. Execute this
#	   remediation AFTER testing on a non-production
#	   system!

apt-get remove --purge ntpdate
# END fix for 'package_ntpdate_removed'

###############################################################################
# BEGIN fix (30 / 41) for 'package_auditd_installed'
###############################################################################
(>&2 echo "Remediating rule 30/41: 'package_auditd_installed'")
# Include source function library.

apt-get install auditd
# END fix for 'package_auditd_installed'

###############################################################################
# BEGIN fix (31 / 41) for 'service_auditd_enabled'
###############################################################################
(>&2 echo "Remediating rule 31/41: 'service_auditd_enabled'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'service_auditd_enabled'

###############################################################################
# BEGIN fix (32 / 41) for 'package_cron_installed'
###############################################################################
(>&2 echo "Remediating rule 32/41: 'package_cron_installed'")
# Include source function library.

apt-get install cron
# END fix for 'package_cron_installed'

###############################################################################
# BEGIN fix (33 / 41) for 'package_ntp_installed'
###############################################################################
(>&2 echo "Remediating rule 33/41: 'package_ntp_installed'")
# Include source function library.

apt-get install ntp
# END fix for 'package_ntp_installed'

###############################################################################
# BEGIN fix (34 / 41) for 'service_ntp_enabled'
###############################################################################
(>&2 echo "Remediating rule 34/41: 'service_ntp_enabled'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'service_ntp_enabled'

###############################################################################
# BEGIN fix (35 / 41) for 'apt_conf_disallow_unauthenticated'
###############################################################################
(>&2 echo "Remediating rule 35/41: 'apt_conf_disallow_unauthenticated'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'apt_conf_disallow_unauthenticated'

###############################################################################
# BEGIN fix (36 / 41) for 'apt_sources_list_official'
###############################################################################
(>&2 echo "Remediating rule 36/41: 'apt_sources_list_official'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'apt_sources_list_official'

###############################################################################
# BEGIN fix (37 / 41) for 'sshd_allow_only_protocol2'
###############################################################################
(>&2 echo "Remediating rule 37/41: 'sshd_allow_only_protocol2'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sshd_allow_only_protocol2'

###############################################################################
# BEGIN fix (38 / 41) for 'sshd_set_idle_timeout'
###############################################################################
(>&2 echo "Remediating rule 38/41: 'sshd_set_idle_timeout'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sshd_set_idle_timeout'

###############################################################################
# BEGIN fix (39 / 41) for 'sshd_set_keepalive'
###############################################################################
(>&2 echo "Remediating rule 39/41: 'sshd_set_keepalive'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sshd_set_keepalive'

###############################################################################
# BEGIN fix (40 / 41) for 'sshd_disable_root_login'
###############################################################################
(>&2 echo "Remediating rule 40/41: 'sshd_disable_root_login'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sshd_disable_root_login'

###############################################################################
# BEGIN fix (41 / 41) for 'sshd_disable_empty_passwords'
###############################################################################
(>&2 echo "Remediating rule 41/41: 'sshd_disable_empty_passwords'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'sshd_disable_empty_passwords'

